# MythicBedwars Configuration
# Acting progression multipliers
acting:
  # Base amount of acting gained per second
  passive-amount: 10
  # Multiplier for passive acting gain
  passive-multiplier: 1.0
  # Multiplier for kills
  kill-multiplier: 5.0
  # Multiplier for final kills
  final-kill-multiplier: 7.0
  # Multiplier for breaking enemy beds
  bed-break-multiplier: 10.0

statistics:
  save-interval-seconds: 300