# MythicBedwars Configuration

# Skip ritual requirements for sequences in Bedwars
skip-rituals: true

# Acting progression multipliers
acting:
  # Base amount of acting gained per second
  passive-amount: 10
  # Multiplier for passive acting gain
  passive-multiplier: 1.0
  # Multiplier for kills
  kill-multiplier: 5.0
  # Multiplier for final kills
  final-kill-multiplier: 7.0
  # Multiplier for breaking enemy beds
  bed-break-multiplier: 10.0

# Potion prices per sequence
# Available currencies: iron, gold, diamond, emerald
potion-prices:
  9:
    iron: 0
    gold: 20
    diamond: 0
    emerald: 0
  8:
    iron: 0
    gold: 40
    diamond: 0
    emerald: 0
  7:
    iron: 0
    gold: 0
    diamond: 12
    emerald: 0
  6:
    iron: 0
    gold: 0
    diamond: 24
    emerald: 0
  5:
    iron: 0
    gold: 0
    diamond: 0
    emerald: 4
  4:
    iron: 0
    gold: 0
    diamond: 0
    emerald: 8
  3:
    iron: 0
    gold: 0
    diamond: 0
    emerald: 16
  2:
    iron: 0
    gold: 0
    diamond: 0
    emerald: 32
  1:
    iron: 0
    gold: 0
    diamond: 0
    emerald: 64
  0:
    iron: 0
    gold: 0
    diamond: 0
    emerald: 128